//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projetoEntities2UNIP : DbContext
    {
        public projetoEntities2UNIP()
            : base("name=projetoEntities2UNIP")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CERTIFICADO> CERTIFICADO { get; set; }
        public virtual DbSet<COORDENADOR> COORDENADOR { get; set; }
        public virtual DbSet<PALESTRA> PALESTRA { get; set; }
        public virtual DbSet<pessoa> pessoa { get; set; }
    }
}
