//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pessoa
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string curso { get; set; }
        public string ra { get; set; }
        public string rg { get; set; }
        public string senha { get; set; }
        public string chave { get; set; }
        public Nullable<System.DateTime> hent { get; set; }
        public Nullable<System.DateTime> hsai { get; set; }
    }
}
