<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="grid.aspx.cs" Inherits="UNIP.Html.grid" %>

<%--Link secundario para conectar ao banco de dados--%>
<%--<%@ Import Namespace="System.Data.SqlClient" %>--%>
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <link href="../CSS/estilo.css" rel="stylesheet" />
    <title></title>
    <%--CSS inline--%>
    <style>
        section#formulario2 {
            position: absolute;
            top: 50%;
            left: 50%;
            margin-left: -350px;
            margin-top: -300px;
            width: 700px;
            min-height: 100px;
            background-color: white;
            overflow: hidden;
            border-radius: 5px;
        }
    </style>

</head>
<body>
    <form id="form1" runat="server">

        <section id="formulario2">

            <p id="titulo">Gerenciar Palestra</p>

            <%--Link secundario para conectar ao banco de dados--%>

            <%--<% SqlConnection conexao = new SqlConnection("Data Source=localhost;Initial Catalog=ACESSO;Persist Security Info=True;User ID=sa;Password=1234");
           conexao.Open();
           string sql="Select * from PALESTRA";
           SqlCommand comando = new SqlCommand(sql, conexao);
           SqlDataReader linhas = comando.ExecuteReader();
           while(linhas.Read())
           {
           }
       %>--%>

            <%--GridView mostrado em tela com edit e delete--%>

            <asp:GridView ID="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" ForeColor="#333333" GridLines="None" OnSelectedIndexChanged="GridView1_SelectedIndexChanged1" DataKeyNames="ID" DataSourceID="SqlDataSource1" Width="700px">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:BoundField DataField="ID" HeaderText="ID" SortExpression="ID" InsertVisible="False" ReadOnly="True" />
                    <asp:BoundField DataField="NOME" HeaderText="NOME" SortExpression="NOME" />
                    <asp:BoundField DataField="EMAIL" HeaderText="EMAIL" SortExpression="EMAIL" />
                    <asp:BoundField DataField="TEMA" HeaderText="TEMA" SortExpression="TEMA" />
                    <asp:BoundField DataField="HORA" HeaderText="HORA" SortExpression="HORA" />
                    <asp:BoundField DataField="DATA" HeaderText="DATA" SortExpression="DATA" />
                </Columns>
                <EditRowStyle BackColor="#7C6F57" />
                <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#E3EAEB" />
                <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F8FAFA" />
                <SortedAscendingHeaderStyle BackColor="#246B61" />
                <SortedDescendingCellStyle BackColor="#D4DFE1" />
                <SortedDescendingHeaderStyle BackColor="#15524A" />
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:projetoConnectionString4 %>" DeleteCommand="DELETE FROM [PALESTRA] WHERE [ID] = @ID" InsertCommand="INSERT INTO [PALESTRA] ([NOME], [EMAIL], [TEMA], [HORA], [DATA]) VALUES (@NOME, @EMAIL, @TEMA, @HORA, @DATA)" SelectCommand="SELECT [ID], [NOME], [EMAIL], [TEMA], [HORA], [DATA] FROM [PALESTRA]" UpdateCommand="UPDATE [PALESTRA] SET [NOME] = @NOME, [EMAIL] = @EMAIL, [TEMA] = @TEMA, [HORA] = @HORA, [DATA] = @DATA WHERE [ID] = @ID">
                <DeleteParameters>
                    <asp:Parameter Name="ID" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="NOME" Type="String" />
                    <asp:Parameter Name="EMAIL" Type="String" />
                    <asp:Parameter Name="TEMA" Type="String" />
                    <asp:Parameter Name="HORA" Type="String" />
                    <asp:Parameter Name="DATA" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="NOME" Type="String" />
                    <asp:Parameter Name="EMAIL" Type="String" />
                    <asp:Parameter Name="TEMA" Type="String" />
                    <asp:Parameter Name="HORA" Type="String" />
                    <asp:Parameter Name="DATA" Type="String" />
                    <asp:Parameter Name="ID" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <asp:Button ID="btnHome" runat="server" Text="HOME" PostBackUrl="~/index.aspx" CssClass="btn" />

            <asp:Button ID="Button1" runat="server" Text="Voltar" PostBackUrl="~/Html/PalestraC.aspx" CssClass="btn" />
        </section>
    </form>
</body>
</html>
